### ISSUE TITLE
[Suggestion] Change Config format from ".conf" to ".json"

### ISSUE THREAD

**Issue by Delfite** [SFort/MC-betterbeacon#6]
Minecraft Version: 1.18.2
Mod Loader: Fabric
Mod Name: Better Beacon
Mod Version: 1.0.8

Suggestion: Change the file format used for your mod's config file from the unformatted, horrendous-looking, and unintuitive ".conf" to ".json" like what 99% of other mods have done. ".conf" has no proper formatting, looks awful, and feels laughably unintuitive to use as a modpack maker. ".conf" also can't be used to make an in-game config screen if one is to ever be added to this mod.

Seriously, please consider updating your mod's config format to something SIGNIFICANTLY better than what you have currently.

Edit: To add on to this suggestion, add some text in the config that clarifies that beacon range is determined by chunks and not blocks like I mistakenly thought when I first used this mod. Also, add an option to toggle between blocks and chunks for determining a beacon's range.

**Comment by SFort** [comment]
".conf" isn't a real format it's just generic for config file, anything could be in the file.
yes it's horrendus.

the reason the config for my mods is as it is atm is as follows:
my first mod with a config had a file with a single value in it, zero formatting.
when i needed to add more values i just went fuck it let's just use every other line as one.
(since i was being lazy and not wanting to re-format)
it's an increadibly stupid config format.

however it does not ""prevent making an in-game config screen"" any format is compleatly irrelavent to that.

the problem is i`m increadibly indecicive on it and can't decide on a format,

json:
 is a bit overcomplicated and the only way to do comments in it is to have ignored values, it's also not very readable.

maybe ini?
but it also has very little benefit over the current config.
it would be better since it would make it slightly clearer and wouldn't lock the ordering.
it might cause issues with comment duplication if someone added their own comments.
it would also not resolve the multiline value issue, though this can be solved by ripping toml's arrays.

maybe just straight up toml?
but then the file would allow comments and values in the same line and i don't really want to deal with that.

i dunno afther writing this i guess it would be ini with toml arrays.
but i don't think it's worth the time to switch formats, 
rather work on adding features, fixing bugs or even porting BS.
(well in reality i'll be spending the weekend playing tf2)

because this is a minor issue that ppl can easily get used to and doesn't affect gameplay in any way, 
still i assume i'll change the format at some point now that i've actually come to somesorta semi-reasonable solution, but i doubt it will be any time soon

**Comment by Delfite** [comment]
![sodium-options json](https://user-images.githubusercontent.com/23504262/202778627-aa388d34-4ce6-41e2-ae4e-404a27ddb4ed.PNG)
This is `sodium-options.json` in the text editor "Sublime".
![bro-wtf1](https://user-images.githubusercontent.com/23504262/202778796-c85fe8db-5366-4ebf-92bb-7999102e1945.PNG)
This is your config in the same text editor. I think I know which file format I would use if I was making a mod.

In fact, I did make a mod using JSON, just not for Minecraft:
![audio_replacements json](https://user-images.githubusercontent.com/23504262/202780393-f1e148d0-9bd2-486f-ac34-ea287202f8c9.PNG)


While modding with JSON can be different depending on the game, the difference is clear on which config type is better overall. If you wanna keep it as CONF then sure, you do you. Though, considering how many comments are on your mod page denoting how many issues have arisen as a result of the awful and hard-to-read layout, I would still HIGHLY advise you change it to JSON.

Also, thanks for letting me know that making a config is more universal than I thought. I had no idea you could make it whatever you wanted until now 👍

**Comment by SFort** [comment]
i don't wanna keep it as the current config, i said so in the comment above?

also JSON does NOT allow comments whatever config you made is NOT JSON. [see Wikipedia for reason](https://en.wikipedia.org/wiki/JSON#Data_types)

it's not intended for a config file and is actually really bad for it.
it's also harder to write then something that's indeded as a config like ini or yaml.

i will eventually switch to a config standard which will mean your text editor will have pretty colors but it will absolutley not be json

**Comment by SFort** [comment]
changed in 1.1.0.
left is IntelliJ, right is neovim, i don't have sublime installed but .ini is very common and i'm sure it too has pretty colors, enjoy.

![screenshot](https://user-images.githubusercontent.com/1879846/211693170-f58ae3c4-79fb-4704-baa4-374f4812f3e3.png)
