### ISSUE TITLE
[Request] Effect level

### ISSUE THREAD

**Issue by evoandroidevo** [SFort/MC-betterbeacon#9]
Is it possible to add any customization to the level of effects based on the blocks being used in the beacon base.

**Comment by SFort** [comment]
it sure is possible, here's ([0001-Beacon-level.patch](https://github.com/SFort/MC-betterbeacon/files/12385299/0001-Beacon-level.patch.txt)) an example patch that makes it add 2 levels if  a netherite block is present.
feel free to use / change said patch to get what you're looking for.



not adding it to the mod though because i don't have a good way to make it configurable.
